create table if not exists public.niim_events (
  id bigint generated by default as identity primary key,
  type text not null,
  device_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.niim_authorized_users (
  email text primary key,
  created_at timestamptz not null default now()
);

alter table public.niim_events enable row level security;
alter table public.niim_authorized_users enable row level security;

-- Add your approved login email after creating the Supabase Auth user.
-- Example:
-- insert into public.niim_authorized_users (email)
-- values ('your-email@example.com')
-- on conflict (email) do nothing;
