create table if not exists public.niim_auth (
  id text primary key default 'main',
  device_id text not null,
  secret text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.niim_events (
  id bigint generated by default as identity primary key,
  type text not null,
  device_id text,
  created_at timestamptz not null default now()
);

alter table public.niim_auth enable row level security;
alter table public.niim_events enable row level security;
